---
controller_execution_environments:
  - name: "Automation Hub Minimal execution environment"
    description: ""
    image: "172.16.1.47/ee-minimal-rhel8:latest"
    pull: ""
    credential: "Automation Hub Container Registry"
  - name: "Automation Hub Ansible Engine 2.9 execution environment"
    description: ""
    image: "172.16.1.47/ee-29-rhel8:latest"
    pull: ""
    credential: "Automation Hub Container Registry"
  - name: "Automation Hub Default execution environment"
    description: ""
    image: "172.16.1.47/ee-supported-rhel8:latest"
    pull: ""
    credential: "Automation Hub Container Registry"
  - name: "Control Plane Execution Environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest"
    pull: ""
    credential: "Default Execution Environment Registry Credential"
  - name: "CUSTOM: Collections Supported (AAP2.3)"
    description: ""
    image: "quay.io/rh_ee_cparada/ee-supported-rh-cparada-23:latest"
    pull: "always"
    credential: "quay.io"
  - name: "CUSTOM: Collections Supported Fortinet (AAP2.3)"
    description: ""
    image: "quay.io/rh_ee_cparada/ee-supported-rh-cparada-fortinet-23:latest"
    pull: "always"
  - name: "Default execution environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest"
    pull: "always"
    credential: "Default Execution Environment Registry Credential"
  - name: "Ansible Engine 2.9 execution environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-23/ee-29-rhel8:latest"
    pull: ""
    credential: "Default Execution Environment Registry Credential"
  - name: "Minimal execution environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest"
    pull: ""
    credential: "Default Execution Environment Registry Credential"
  - name: "CUSTOM: Collections Minimal Cisco (AAP2.3)"
    description: ""
    image: "quay.io/rh_ee_cparada/ee-minimal-rh-cparada-cisco-23:latest"
    pull: "always"
    credential: "quay.io"
  - name: "CUSTOM AH: Collections Minimal Cisco (AAP2.3)"
    description: ""
    image: "172.16.1.47/ee-minimal-rh-cparada-cisco-23:latest"
    pull: "always"
    credential: "Automation Hub Container Registry"
  - name: "CUSTOM AH: Collections Supported (AAP2.3)"
    description: ""
    image: "172.16.1.47/ee-supported-rh-cparada-23:latest"
    pull: "always"
    credential: "Automation Hub Container Registry"
  - name: "CUSTOM AH: Collections Supported Fortinet (AAP2.3)"
    description: ""
    image: "172.16.1.47/ee-supported-rh-cparada-fortinet-23:latest"
    pull: "always"
    credential: "Automation Hub Container Registry"
  - name: "CUSTOM AH: Collections Minimal Azure (AAP2.3)"
    description: ""
    image: "172.16.1.47/ee-supported-rh-cparada-azure-23"
    pull: "always"
    credential: "Automation Hub Container Registry"
  - name: "CUSTOM AH: Collections Supported Paloalto (AAP2.3)"
    description: ""
    image: "172.16.1.47/ee-supported-rh-cparada-paloalto-23:latest"
    pull: "always"
    credential: "Automation Hub Container Registry"
...
